name: zoommil
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
    - python==3.7
    - tensorboard>=2.0.0
    - scikit-learn>=1.0
    - pandas>=1.3.3
    - tqdm
    - matplotlib>=3.1.1
    - seaborn
    - pillow
    - pip
    - pip:
        - h5py>=2.9.0
        - opencv-python>=4.5.3.56
        - scikit-image>=0.18.3
        - dgl==0.4.3.post2